---
- name: Create a new EC2 instance
  hosts: localhost
  gather_facts: False
  vars:
      region: ap-south-1
      instance_type: t2.nano
      ami: ami-dd3442b2
      keypair: cc-interview-niraj
      ansible_python_interpreter: /usr/bin/python3 
  tasks:
    - name: Create an ec2 instance
      ec2:
         key_name: "{{ keypair }}"
         group_id: sg-c61ab8af
         instance_type: "{{ instance_type}}"
         image: "{{ ami }}"
         wait: true
         region: "{{ region }}"
         count: 1  # default
         count_tag:
            Name: CCInterview
         instance_tags:
            Name: CCInterview
         vpc_subnet_id: subnet-79cf2910
         assign_public_ip: yes
      register: ec2
    - name: Wait for the instances to boot by checking the ssh port
      wait_for: 
        host: "{{item.public_dns_name}}" 
        port: 22 
        delay: 60 
        timeout: 460 
        state: started
      with_items: "{{ ec2.instances }}"
    - name: Add new instances to host group
      add_host: hostname="{{item.public_ip}}" groupname=ec2
      with_items: "{{ ec2.instances }}"

- name: Configure Instances
  hosts: ec2
  user: ubuntu
  become: yes
  vars:
      ansible_ssh_private_key_file: /root/.ssh/aws.niraj.pem
      ansible_python_interpreter: /usr/bin/python3
  tasks:
    - set_fact: mydate="{{lookup('pipe','date +%Y%m%d%H%M%S')}}"
    - name: install nginx
      apt: name=nginx state=latest
    - name: Backup Existing index.html
      copy: src=/usr/share/nginx/html/index.html dest=/usr/share/nginx/html/index.html."{{ mydate }}"
      remote_src: yes
    - name: copy nginx.conf
      copy: src=nginx.conf dest=/etc/nginx/nginx.conf
    - name: copy default
      copy: src=default dest=/etc/nginx/sites-available/default
    - name: copy index.html
      copy: src=index.html dest=/usr/share/nginx/html/index.html
    - name: index.html to /var/www/html
      copy: src=index.html dest=/var/www/html/index.html
    - name: start nginx service
      service: name=nginx enabled=yes state=started 
